language: ruby
sudo: false
rvm:
 - 2.2.5
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
script:
 - bundle exec jekyll build
 - bundle exec htmlproofer ./_site/ --href-ignore \# --check-html
