language: ruby
sudo: false
rvm:
 - 2.2.5
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
addons:
  apt:
    packages: bundle  
script:
 - bundle exec jekyll build
 - bundle exec htmlproofer ./_site/ --allow-hash-href --check-html
