# Site settings
name: ZoneMinder
title: Linux video camera security and surveillance solution.
email: your-email@domain.com
description: "A full-featured, open source, state-of-the-art video surveillance software system."
baseurl: ""
url: "https://zoneminder.com"

# Build settings
markdown: kramdown
permalinks: pretty

# Links
permalink: /blog/:categories/:year/:month/:day/:title.html
